export const userPictureData = [
  {
    _id: '653c27770ea9a2e7ee210348',
    userID: '653c27770ea9a2e7ee210347',
    username: 'briana30',
    pictureData: {
      paper: 1976,
      cardboard: 1914,
      compost: 1996,
      metal: 1814,
      glass: 1909,
      plastic: 1922,
      trash: 1916,
      other: 1848,
      unknown: 0,
    },
    totalUploads: 15295,
  },
  {
    _id: 2,
    userID: 2,
    username: 'Deke M. Pose',
    pictureData: {
      paper: 12,
      cardboard: 4,
      compost: 6,
      metal: 2,
      glass: 8,
      plastic: 7,
      trash: 10,
      other: 3,
      unknown: 1,
    },
    totalUploads: 52,
  },
  {
    _id: 3,
    userID: 3,
    username: 'Al U. Minnum',
    pictureData: {
      paper: 2,
      cardboard: 3,
      compost: 7,
      metal: 23,
      glass: 7,
      plastic: 7,
      trash: 4,
      other: 9,
      unknown: 3,
    },
    totalUploads: 65,
  },
  {
    _id: 4,
    userID: 4,
    username: 'Polly Esther',
    pictureData: {
      paper: 21,
      cardboard: 33,
      compost: 17,
      metal: 3,
      glass: 27,
      plastic: 19,
      trash: 30,
      other: 31,
      unknown: 4,
    },
    totalUploads: 185,
  },
  {
    _id: 5,
    userID: 5,
    username: 'Lan D. Phil',
    pictureData: {
      paper: 1,
      cardboard: 2,
      compost: 7,
      metal: 8,
      glass: 12,
      plastic: 9,
      trash: 6,
      other: 0,
      unknown: 2,
    },
    totalUploads: 47,
  },
  {
    _id: 6,
    userID: 6,
    username: 'Recy Claire',
    pictureData: {
      paper: 1,
      cardboard: 0,
      compost: 2,
      metal: 0,
      glass: 0,
      plastic: 3,
      trash: 1,
      other: 2,
      unknown: 0,
    },
    totalUploads: 9,
  },
  {
    _id: 7,
    userID: 7,
    username: 'Litter Lee',
    pictureData: {
      paper: 0,
      cardboard: 3,
      compost: 5,
      metal: 4,
      glass: 2,
      plastic: 7,
      trash: 10,
      other: 2,
      unknown: 3,
    },
    totalUploads: 36,
  },
  {
    _id: 8,
    userID: 8,
    username: 'Refuse Robinson',
    pictureData: {
      paper: 100,
      cardboard: 123,
      compost: 96,
      metal: 102,
      glass: 122,
      plastic: 99,
      trash: 104,
      other: 101,
      unknown: 132,
    },
    totalUploads: 979,
  },
  {
    _id: 9,
    userID: 9,
    username: 'Garbella Greenfield',
    pictureData: {
      paper: 13,
      cardboard: 22,
      compost: 71,
      metal: 88,
      glass: 125,
      plastic: 94,
      trash: 63,
      other: 80,
      unknown: 22,
    },
    totalUploads: 578,
  },
  {
    _id: 10,
    userID: 10,
    username: 'Binjamin Franklin',
    pictureData: {
      paper: 55,
      cardboard: 22,
      compost: 38,
      metal: 41,
      glass: 74,
      plastic: 36,
      trash: 27,
      other: 81,
      unknown: 58,
    },
    totalUploads: 432,
  },
  {
    _id: 11,
    userID: 11,
    username: 'Rubi Canfield',
    pictureData: {
      paper: 4,
      cardboard: 9,
      compost: 5,
      metal: 6,
      glass: 29,
      plastic: 3,
      trash: 2,
      other: 10,
      unknown: 3,
    },
    totalUploads: 71,
  },
  {
    _id: 12,
    userID: 12,
    username: 'Litterton Steele',
    pictureData: {
      paper: 14,
      cardboard: 18,
      compost: 12,
      metal: 13,
      glass: 19,
      plastic: 15,
      trash: 16,
      other: 10,
      unknown: 12,
    },
    totalUploads: 129,
  },
];

export const userData = [
  {
    _id: 1,
    email: 'reesespeaches@email.com',
    password: 'password',
    username: 'reeseoroni',
    firstName: 'Reese',
    lastName: 'Ikler',
  },
  {
    _id: 2,
    email: 'email@email.com',
    password: 'password',
    username: 'Deke M. Pose',
    firstName: 'Deke',
    lastName: 'Pose',
  },
  {
    _id: 3,
    email: 'email@email.com',
    password: 'password',
    username: 'Al U. Minnum',
    firstName: 'Al',
    lastName: 'Minnum',
  },
  {
    _id: 4,
    email: 'email@email.com',
    password: 'password',
    username: 'Polly Esther',
    firstName: 'Polly',
    lastName: 'Esther',
  },
  {
    _id: 5,
    email: 'email@email.com',
    password: 'password',
    username: 'Lan D. Phil',
    firstName: 'Lan',
    lastName: 'Phil',
  },
  {
    _id: 6,
    email: 'email@email.com',
    password: 'password',
    username: 'Recy Claire',
    firstName: 'Recy',
    lastName: 'Claire',
  },
  {
    _id: 7,
    email: 'email@email.com',
    password: 'password',
    username: 'Litter Lee',
    firstName: 'Litter',
    lastName: 'Lee',
  },
  {
    _id: 8,
    email: 'email@email.com',
    password: 'password',
    username: 'Refuse Robinson',
    firstName: 'Refuse',
    lastName: 'Robinson',
  },
  {
    _id: 9,
    email: 'email@email.com',
    password: 'password',
    username: 'Garbella Greenfield',
    firstName: 'Garbella',
    lastName: 'Greenfield',
  },
  {
    _id: 10,
    email: 'email@email.com',
    password: 'password',
    username: 'Binjamin Franklin',
    firstName: 'Binjamin',
    lastName: 'Franklin',
  },
  {
    _id: 11,
    email: 'email@email.com',
    password: 'password',
    username: 'Rubi Canfield',
    firstName: 'Rubi',
    lastName: 'Canfield',
  },
  {
    _id: 12,
    email: 'email@email.com',
    password: 'password',
    username: 'Litterton Steele',
    firstName: 'Litterton',
    lastName: 'Steele',
  },
];
